name: BK Zip Deploy
author: lovneet, BK
description: "Create zip of existing code then send zip to webhook for deployment, fork of mkyai/zip-deploy. But added max buffer size"
branding:
  icon: "file"
  color: green
inputs:
  webhook:
    description: "Deployment webhook to handle @code.zip file"
    required: false
  secret:
    description: "Webhook secret for request verification"
    required: false

outputs:
  env:
    description: "Deployment successfull"
runs:
  using: "node16"
  main: "dist/index.js"
